###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################


####
# nodejs variables
####
#@appUrl = http://127.0.0.1:5300
#@Dapr-appUrl = http://127.0.0.1:3500
#@Dapr-appName = nodeapp

####
# python variables
####
#@appUrl = http://localhost:5400
#@Dapr-appUrl = http://localhost:3600
#@Dapr-appName = pythonapp


####
# golang variables
####
#@appUrl = http://localhost:5500
#@Dapr-appUrl = http://localhost:3700
#@Dapr-appName = golangapp


####
# dotnet
####
@appUrl = https://localhost:5601
@Dapr-appUrl = http://127.0.0.1:3800
@Dapr-appName = dotnetapp


### Check the Home page
GET {{appUrl}} HTTP/1.1


### The Health Check
GET {{appUrl}}/hc HTTP/1.1


### Check simple post
POST {{appUrl}}/Order/submit HTTP/1.1
Content-Type: application/json

{
    "data": {
        "id": "123456",
        "description": "Simple test"
    }
}


### Dapr Version - Check the Home page
GET {{Dapr-appUrl}}/v1.0/invoke/{{Dapr-appName}}/method HTTP/1.1

### Dapr Version - Health Check
GET {{Dapr-appUrl}}/v1.0/invoke/{{Dapr-appName}}/method/hc HTTP/1.1

### Dapr Version - Check simple post
POST {{Dapr-appUrl}}/v1.0/invoke/{{Dapr-appName}}/method/order/submit HTTP/1.1
Content-Type: application/json

{
    "data": {
        "id": "{{$guid}}",
        "description": "{{$randomAdjective}}"
    }
}
