apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: genocs
  name: foo-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
    spec:
      containers:
        - name: api
          image: genocs/foo
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: genocs
  name: genocs-foo-service
  labels:
    app: genocs-foo-service
spec:
  type: LoadBalancer
  selector:
    app: foo
  ports:
    - name: http
      protocol: TCP
      port: 5300
      targetPort: 5000