apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: genocs
  name: genocs-golang-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
        - name: api
          image: genocs/golang
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: genocs
  name: genocs-golang-service
  labels:
    app: genocs-golang-service
spec:
  type: LoadBalancer
  selector:
    app: golang
  ports:
    - name: http
      protocol: TCP
      port: 5500
      targetPort: 8080