apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: genocs
  name: genocs-nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
        - name: api
          image: genocs/nodejs
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: genocs
  name: genocs-nodejs-service
  labels:
    app: genocs-nodejs-service
spec:
  type: LoadBalancer
  selector:
    app: nodejs
  ports:
    - name: http
      protocol: TCP
      port: 5400
      targetPort: 3000