apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: genocs
  name: genocs-python-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
        - name: api
          image: genocs/python
          ports:
            - containerPort: 5400
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service
metadata:
  namespace: genocs
  name: genocs-python-service
  labels:
    app: genocs-python-service
spec:
  type: LoadBalancer
  selector:
    app: python
  ports:
    - name: http
      protocol: TCP
      port: 5400
      targetPort: 5400