###############################################################################
# Use this file inside Visual Studio code with 'REST Client' plugin 
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
###############################################################################


####
# nodejs variables
####
@appUrl = http://localhost:5300
@Dapr-appUrl = http://localhost:3500
@Dapr-appName = nodeapp

####
# python variables
####
#@appUrl = http://localhost:5400
#@Dapr-appUrl = http://localhost:3600
#@Dapr-appName = pythonapp


####
# golang variables
####
#@appUrl = http://localhost:5500
#@Dapr-appUrl = http://localhost:3700
#@Dapr-appName = golangapp



### Check the Home page
GET {{appUrl}} HTTP/1.1


### Check the ping
GET {{appUrl}}/ping HTTP/1.1


### Check simple post
POST {{appUrl}}/post_my_data HTTP/1.1
header : "Content-Type": "application/json"

{
    "data": {
        "id": "{{$guid}}"
    }    
}


### Dapr Version - Check the Home page
GET {{Dapr-appUrl}}/v1.0/invoke/{{Dapr-appName}}/method HTTP/1.1

### Dapr Version - Check the ping
GET {{Dapr-appUrl}}/v1.0/invoke/{{Dapr-appName}}/method/ping HTTP/1.1

### Dapr Version - Check simple post
POST {{Dapr-appUrl}}/v1.0/invoke/{{Dapr-appName}}/method/post_my_data HTTP/1.1
header : "Content-Type": "application/json"

{
    "data": {
        "id": "{{$guid}}"
    }
}