version: "3.8"

services:
  api:
    image: genocs/genocs.microservices.api
    container_name: api
    ports:
      - 5000:5000
    networks:
      - genocs

  identity-service:
    image: genocs/genocs.microservices.identity
    container_name: identity-service
    ports:
      - 5002:5000
    networks:
      - genocs

  notifications-service:
    image: genocs/genocs.microservices.notifications
    container_name: notifications-service
    ports:
      - 5003:5000
    networks:
      - genocs

  operations-service:
    image: genocs/genocs.microservices.operations
    container_name: operations-service
    ports:
      - 5001:5000
    networks:
      - genocs

  signalr-service:
    image: genocs/genocs.microservices.signalr
    container_name: signalr-service
    ports:
      - 5007:5000
    networks:
      - genocs

  production-service:
    image: genocs/genocs.microservices.production
    container_name: production-service
    ports:
      - 5004:5000
    networks:
      - genocs

# The network is supposed been created by the infrastructure 
networks:
  genocs:
    name: genocs-network
    external: true
